/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import javax.swing.JDesktopPane;

/**
 *
 * @author Cassio
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        btnCadastrar = new javax.swing.JMenu();
        CadastrarHoras = new javax.swing.JMenuItem();
        menuFerias = new javax.swing.JMenu();
        menuFeriasVencidas = new javax.swing.JMenuItem();
        menuFeriasTiradas = new javax.swing.JMenuItem();
        btnConsultar = new javax.swing.JMenu();
        menuConsultarHoras = new javax.swing.JMenuItem();
        menuConsultarFerias = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        btnCadastrar.setText("Cadastrar");

        CadastrarHoras.setText("Horas");
        CadastrarHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarHorasActionPerformed(evt);
            }
        });
        btnCadastrar.add(CadastrarHoras);

        menuFerias.setText("Férias");

        menuFeriasVencidas.setText("Vencidas");
        menuFeriasVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFeriasVencidasActionPerformed(evt);
            }
        });
        menuFerias.add(menuFeriasVencidas);

        menuFeriasTiradas.setText("Tiradas");
        menuFeriasTiradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFeriasTiradasActionPerformed(evt);
            }
        });
        menuFerias.add(menuFeriasTiradas);

        btnCadastrar.add(menuFerias);

        jMenuBar2.add(btnCadastrar);

        btnConsultar.setText("Consultar");

        menuConsultarHoras.setText("Horas");
        menuConsultarHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarHorasActionPerformed(evt);
            }
        });
        btnConsultar.add(menuConsultarHoras);

        menuConsultarFerias.setText("Férias");
        menuConsultarFerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarFeriasActionPerformed(evt);
            }
        });
        btnConsultar.add(menuConsultarFerias);

        jMenuBar2.add(btnConsultar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFeriasVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFeriasVencidasActionPerformed
CadastraFeriasV cadastrav = new CadastraFeriasV();
                
                jDesktopPane1.add(cadastrav);
               cadastrav.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuFeriasVencidasActionPerformed

    private void menuFeriasTiradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFeriasTiradasActionPerformed
        CadastraFeriasT cadastrat = new CadastraFeriasT();
                
                jDesktopPane1.add(cadastrat);
               cadastrat.setVisible(true);  
    }//GEN-LAST:event_menuFeriasTiradasActionPerformed

    private void menuConsultarFeriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarFeriasActionPerformed
            ConsultaFerias consultaf = new ConsultaFerias();
            jDesktopPane1.add(consultaf);
            
            consultaf.setVisible(true);
    }//GEN-LAST:event_menuConsultarFeriasActionPerformed

    private void menuConsultarHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarHorasActionPerformed
ConsultaHoras consultah = new ConsultaHoras();
            jDesktopPane1.add(consultah);
            consultah.setVisible(true);
                                                    // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultarHorasActionPerformed

    private void CadastrarHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarHorasActionPerformed
                CadastraHoras cadastrah = new CadastraHoras();
                
                jDesktopPane1.add(cadastrah);
               cadastrah.setVisible(true);
                        
    }//GEN-LAST:event_CadastrarHorasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarHoras;
    private javax.swing.JMenu btnCadastrar;
    private javax.swing.JMenu btnConsultar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuConsultarFerias;
    private javax.swing.JMenuItem menuConsultarHoras;
    private javax.swing.JMenu menuFerias;
    private javax.swing.JMenuItem menuFeriasTiradas;
    private javax.swing.JMenuItem menuFeriasVencidas;
    // End of variables declaration//GEN-END:variables
}
